# Generated by Django 5.0.1 on 2024-01-18 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('nationality', models.CharField(max_length=255)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to='team.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to='team.profile'),
        ),
    ]
