# Generated by Django 5.0.1 on 2024-01-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_profile_player_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile',
        ),
    ]
