# Generated by Django 5.0.1 on 2024-02-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_alter_profile_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsscored',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='team.player', to_field='name'),
        ),
    ]
